### ISSUE TITLE
Cannot install due to require_once path issues

### ISSUE THREAD

**Issue by JKingsnorth** [compucorp/civicrm-aws-sns-sms#2]
https://github.com/compucorp/civicrm-aws-sns-sms/blob/ba678e5ac73de79736d343ed5712ed2a25e6478f/amazonsns.php#L5-L6

These lines need to be made smarter, to load the files from the CiviCRM install. They currently assume these directories are relative? (I was able to install by commenting out these lines).

**Comment by JKingsnorth** [comment]
The module still seems to function even with these lines removed.

**Comment by MiyaNoctem** [comment]
@JKingsnorth, thanks for the feedback. I've set up a PR with the fix if you'd like to review. I'll merge it into develop branch once approved. Here's the link:

PR #3 

Thanks again!

**Comment by JKingsnorth** [comment]
Tested the PR and it looks good to me!

**Comment by MiyaNoctem** [comment]
@JKingsnorth,

PR has been merged into develop branch. Closing issue.
